In [9]:
from random import randrange
import pandas as pd
import string
import random

In [30]:

def random_score_txt(train_txt, train_labels_txt):
    corpus = open(train_txt, encoding="utf-8")
    true_labels = open(train_labels_txt, encoding="utf-8")
    docs_labels = [int(doc.strip()) for doc in true_labels.readlines()]
    docs = [doc.strip() for doc in corpus.readlines()]
    predicted_label = [randrange(2) for i in docs]
    df = pd.DataFrame([docs,docs_labels,predicted_label]).T
    df.columns = ['Text','True_Label', 'Predicted_Label']
    return df

In [29]:
random_score_txt("../datasets/agnews/train.txt","../datasets/agnews/train_labels.txt")

,Text,True_Label,Predicted_Label
0,Wall St. Bears Claw Back Into the Black ( Reut...,2,0
1,Carlyle Looks Toward Commercial Aerospace ( Re...,2,0
2,Oil and Economy Cloud Stocks' Outlook ( Reuter...,2,1
3,Iraq Halts Oil Exports from Main Southern Pipe...,2,0
4,"Oil prices soar to all-time record, posing new...",2,0
...,...,...,...
119995,Pakistan's Musharraf Says Won't Quit as Army C...,0,0
119996,Renteria signing a top-shelf deal. Red Sox gen...,1,0
119997,Saban not going to Dolphins yet. The Miami Dol...,1,0
119998,Today's NFL games. PITTSBURGH at NY GIANTS Tim...,1,0
119999,Nets get Carter from Raptors. INDIANAPOLIS -- ...,1,0

In [51]:
def random_cate_vocab(word, size = 50):
    cate_vocab = []
    occurences = []
    for i in range(size):
        new_word = word
        for j in range(randrange(7)):
            new_word += random.choice(string.ascii_letters)
        cate_vocab.append(new_word)
        occurences.append(randrange(10,10000))
    df = pd.DataFrame([cate_vocab, occurences]).T
    df.columns = ['Vocab', 'Occurences']
    df = (df.sort_values('Occurences', ascending = False)).reset_index(drop = True)
    return df

In [52]:
random_cate_vocab('damn')

         Vocab Occurences
0        damnY       9999
1    damnBSEvW       9565
2     damnThJa       9024
3         damn       8948
4      damnBvX       8909
5         damn       8899
6       damnmM       8388
7    damnwXAUv       8329
8    damntzCuz       7853
9    damnEttZV       7669
10  damnemUDGb       7665
11   damncmACD       7562
12       damnm       7533
13      damnGD       7125
14       damnc       6436
15        damn       5881
16      damnro       5720
17   damnrWCxS       5637
18      damndX       5558
19      damnSP       5546
20     damnUOi       5447
21      damnqE       5338
22      damnCR       5099
23     damngfz       5091
24       damnl       4898
25     damncjB       4620
26      damnNK       4470
27  damnVFLSDc       4241
28  damnfrfwOl       4109
29    damnhuPs       3975
30  damnLImfZZ       3948
31  damnpxhvpQ       3928
32     damncmn       3914
33   damnHVbkK       3897
34   damnuQCYG       3827
35  damnitfSRF       3508
36       damnZ       3290
37     damnedw       3195
38   damnzjnmw       3140
39       damno       3004
40   damnBTIFh       3002
41  damnJcCbjH       2348
42    damnmBEn       1821
43       damnU       1448
44  damnKguZYx       1162
45  damnrUdKyH        998
46   damnenqUJ        854
47    damnaxwM        603
48   damnCppoQ        494
49    damnZpHK        216